### ISSUE TITLE
Crash when zero items to main deck in config

### ISSUE THREAD

**Issue by flipdazed** [flipdazed/SoftwareDevelopment#114]
**Bugged Version** 7249d9c9819450cca49b04fc407137c233f33e31
**File** `actors.py`
**Lines** `105`

**Issue** 
The following deck setup (i.e. initialising as empty causes a crash) The same issue as in #113 due to the hand_size being used to iterate over another list.

```
    "deck_settings":[ # Central deck paramss
        # {"count":4 ,"params":{"name":'Archer', "attack":3, "money":0, "cost":2}},
        # {"count":4 ,"params":{"name":'Baker', "attack":0, "money":3, "cost":2}},
        # {"count":3 ,"params":{"name":'Swordsman', "attack":4, "money":0, "cost":3}},
        # {"count":2 ,"params":{"name":'Knight', "attack":6, "money":0, "cost":5}},
        # {"count":3 ,"params":{"name":'Tailor', "attack":0, "money":4, "cost":3}},
        # {"count":3 ,"params":{"name":'Crossbowman', "attack":4, "money":0, "cost":3}},
        # {"count":3 ,"params":{"name":'Merchant', "attack":0, "money":5, "cost":4}},
        # {"count":4 ,"params":{"name":'Thug', "attack":2, "money":0, "cost":1}},
        # {"count":4 ,"params":{"name":'Thief', "attack":1, "money":1, "cost":1}},
        # {"count":2 ,"params":{"name":'Catapult', "attack":7, "money":0, "cost":6}},
        # {"count":2 ,"params":{"name":'Caravan', "attack":1, "money":5, "cost":5}},
        # {"count":2 ,"params":{"name":'Assassin', "attack":5, "money":0, "cost":4}}
        ]
```

**Fix**
Create an if condition.

**Comment by flipdazed** [comment]
Errored code:

```
def deck_to_active(self):
    """ moves cards from one item to another"""
    for i in xrange(0, self.hand_size):
        card = self.deck.pop()
        self.active.append(card)
        self.logger.debug('iteration #{}: Moving {} from deck to active'.format(i, card.name))
    pass
```

**Comment by flipdazed** [comment]
Fixed code:

**Comment by flipdazed** [comment]
Fixed Code:

```
def deck_to_active(self):
    """ moves cards from one item to another"""
    for i in xrange(0, self.hand_size):

        if len(self.deck) == 0:
            self.logger.debug("Deck length is also zero!")
            self.logger.debug("Exiting the deck_to_active routine as no more cards.")
            return
        card = self.deck.pop()
        self.active.append(card)
        self.logger.debug('iteration #{}: Moving {} from deck to active'.format(i, card.name))
    pass
```

Test:

```
DEBUG: logs: 27: ...running deck_to_active
DEBUG: actors: 107: Deck length is also zero!
DEBUG: actors: 108: Exiting the deck_to_active routine as no more cards.
DEBUG: logs: 27: ...running deck_to_hand
DEBUG: common: 79: Iteration #0: Drawn Squire from deck and added to hand
DEBUG: common: 79: Iteration #1: Drawn Squire from deck and added to hand
```

**Comment by flipdazed** [comment]
**Computer Generated Crash**

```
       Computer is browsing... Money: 3
DEBUG: logs: 27: ...running get_wish_list
DEBUG: actors: 686: Temp purchase list (wish list) initiated
DEBUG: logs: 27: ...running __add_affordable_supplements_to_wishlist
DEBUG: actors: 839: Supplements Detected by Computer
DEBUG: actors: 36: Computer True 1xLevy at cost:2. Added to wish list
DEBUG: logs: 27: ...running __add_affordable_cards_to_wishlist
DEBUG: actors: 54: New desired card index: 0
Traceback (most recent call last):
  File "./cardgame.py", line 41, in <module>
    main(game)
...
    return func(*args, **kwargs)
  File ".../game/actors.py", line 580, in purchase_cards
    self.wish_list = self.get_wish_list()
  File ".../game/logs.py", line 28, in tmp
    return func(*args, **kwargs)
  File ".../actors.py", line 689, in get_wish_list
    self.__add_affordable_cards_to_wishlist()
  File ".../game/logs.py", line 28, in tmp
    return func(*args, **kwargs)
  File ".../game/actors.py", line 824, in __add_affordable_cards_to_wishlist
    card = self.parent.central.active[self.potential_card_index]
IndexError: list index out of range

```

Fix with enumerate

```
def __add_affordable_cards_to_wishlist(self):
    """adds the affordable cards the the wish_list
    expects that self.wish_list exists as a list
    """
    # Select cards where cost of card_i < money
    for self.potential_card_index, card in enumerate(self.parent.central.active):  # Loop all cards
        self.logger_new_desired() # Log the action
        if card.cost <= self.money:   # if PC has enough money
            # Add to temporary purchases
            self.wish_list.append((self.potential_card_index, card))
            self.logger_affords_card(1, card.name, card.cost)  # logger action
        else:
            self.logger_affords_card(1, card.name, card.cost, can_afford=False)  # logger action
    pass
```

**Comment by flipdazed** [comment]
Also seems dodgy... Fix with `enumerate()`

    def buy_card_by_index(self, source):
        """Attempts to buy a card given a source
        
        Expected format of source = integer or 'S'"""
        # This is a card from the active deck
        if source in xrange(0,self.parent.central.hand_size):
            purchase_card = self.parent.central.active[int(source)]

**Comment by flipdazed** [comment]
added handler for when there are no cards:

```
    # exit if no cards
    if not self.card_names:
        error_msg = "Unfortunately no cards could be found in config.py!"
        self.hostile_exit(msg=error_msg)
```

Related Bad Config Formats #116

**Comment by flipdazed** [comment]
^Tested
